/**
 * Sensor Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.1-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "CollectionPost.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

CollectionPost::CollectionPost()
{
    m_Name = utility::conversions::to_string_t("");
    m_Organisationid = utility::conversions::to_string_t("");
    m_GroupidsIsSet = false;
    m__public = false;
    m__publicIsSet = false;
}

CollectionPost::~CollectionPost()
{
}

void CollectionPost::validate()
{
    // TODO: implement validation
}

web::json::value CollectionPost::toJson() const
{
    web::json::value val = web::json::value::object();

    val[utility::conversions::to_string_t("name")] = ModelBase::toJson(m_Name);
    val[utility::conversions::to_string_t("organisationid")] = ModelBase::toJson(m_Organisationid);
    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Groupids )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        if(jsonArray.size() > 0)
        {
            val[utility::conversions::to_string_t("groupids")] = web::json::value::array(jsonArray);
        }
    }
    if(m__publicIsSet)
    {
        val[utility::conversions::to_string_t("public")] = ModelBase::toJson(m__public);
    }

    return val;
}

void CollectionPost::fromJson(web::json::value& val)
{
    setName(ModelBase::stringFromJson(val[utility::conversions::to_string_t("name")]));
    setOrganisationid(ModelBase::stringFromJson(val[utility::conversions::to_string_t("organisationid")]));
    {
        m_Groupids.clear();
        std::vector<web::json::value> jsonArray;
        if(val.has_field(utility::conversions::to_string_t("groupids")))
        {
        for( auto& item : val[utility::conversions::to_string_t("groupids")].as_array() )
        {
            m_Groupids.push_back(ModelBase::stringFromJson(item));
        }
        }
    }
    if(val.has_field(utility::conversions::to_string_t("public")))
    {
        setPublic(ModelBase::boolFromJson(val[utility::conversions::to_string_t("public")]));
    }
}

void CollectionPost::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("name"), m_Name));
    multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("organisationid"), m_Organisationid));
    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Groupids )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        
        if(jsonArray.size() > 0)
        {
            multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("groupids"), web::json::value::array(jsonArray), utility::conversions::to_string_t("application/json")));
        }
    }
    if(m__publicIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("public"), m__public));
    }
}

void CollectionPost::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    setName(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("name"))));
    setOrganisationid(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("organisationid"))));
    {
        m_Groupids.clear();
        if(multipart->hasContent(utility::conversions::to_string_t("groupids")))
        {

        web::json::value jsonArray = web::json::value::parse(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("groupids"))));
        for( auto& item : jsonArray.as_array() )
        {
            m_Groupids.push_back(ModelBase::stringFromJson(item));
        }
        }
    }
    if(multipart->hasContent(utility::conversions::to_string_t("public")))
    {
        setPublic(ModelBase::boolFromHttpContent(multipart->getContent(utility::conversions::to_string_t("public"))));
    }
}

utility::string_t CollectionPost::getName() const
{
    return m_Name;
}


void CollectionPost::setName(utility::string_t value)
{
    m_Name = value;
    
}
utility::string_t CollectionPost::getOrganisationid() const
{
    return m_Organisationid;
}


void CollectionPost::setOrganisationid(utility::string_t value)
{
    m_Organisationid = value;
    
}
std::vector<utility::string_t>& CollectionPost::getGroupids()
{
    return m_Groupids;
}

void CollectionPost::setGroupids(std::vector<utility::string_t> value)
{
    m_Groupids = value;
    m_GroupidsIsSet = true;
}
bool CollectionPost::groupidsIsSet() const
{
    return m_GroupidsIsSet;
}

void CollectionPost::unsetGroupids()
{
    m_GroupidsIsSet = false;
}

bool CollectionPost::isPublic() const
{
    return m__public;
}


void CollectionPost::setPublic(bool value)
{
    m__public = value;
    m__publicIsSet = true;
}
bool CollectionPost::publicIsSet() const
{
    return m__publicIsSet;
}

void CollectionPost::unset_public()
{
    m__publicIsSet = false;
}

}
}
}
}

