/**
 * Sensor Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * CollectionPost.h
 *
 * 
 */

#ifndef CollectionPost_H_
#define CollectionPost_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>
#include <vector>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  CollectionPost
    : public ModelBase
{
public:
    CollectionPost();
    virtual ~CollectionPost();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// CollectionPost members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getName() const;
        void setName(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getOrganisationid() const;
        void setOrganisationid(utility::string_t value);
    /// <summary>
    /// A list of group identifiers for which this stream will be a member.
    /// </summary>
    std::vector<utility::string_t>& getGroupids();
    bool groupidsIsSet() const;
    void unsetGroupids();
    void setGroupids(std::vector<utility::string_t> value);
    /// <summary>
    /// 
    /// </summary>
    bool isPublic() const;
    bool publicIsSet() const;
    void unset_public();
    void setPublic(bool value);

protected:
    utility::string_t m_Name;
        utility::string_t m_Organisationid;
        std::vector<utility::string_t> m_Groupids;
    bool m_GroupidsIsSet;
    bool m__public;
    bool m__publicIsSet;
};

}
}
}
}

#endif /* CollectionPost_H_ */
