/**
 * Sensor Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * GroupCollection__embedded.h
 *
 * 
 */

#ifndef GroupCollection__embedded_H_
#define GroupCollection__embedded_H_


#include "../ModelBase.h"

#include "Group.h"
#include <vector>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  GroupCollection__embedded
    : public ModelBase
{
public:
    GroupCollection__embedded();
    virtual ~GroupCollection__embedded();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// GroupCollection__embedded members

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<Group>>& getGroups();
    bool groupsIsSet() const;
    void unsetGroups();
    void setGroups(std::vector<std::shared_ptr<Group>> value);

protected:
    std::vector<std::shared_ptr<Group>> m_Groups;
    bool m_GroupsIsSet;
};

}
}
}
}

#endif /* GroupCollection__embedded_H_ */
