/**
 * Sensor Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.1-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * Invitation__embedded.h
 *
 * 
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_Invitation__embedded_H_
#define IO_SWAGGER_CLIENT_MODEL_Invitation__embedded_H_


#include "../ModelBase.h"

#include "Organisation.h"
#include "Role.h"
#include <vector>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  Invitation__embedded
    : public ModelBase
{
public:
    Invitation__embedded();
    virtual ~Invitation__embedded();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Invitation__embedded members

    /// <summary>
    /// The organisation the user has been invited to.
    /// </summary>
    std::shared_ptr<Organisation> getOrganisation() const;
    bool organisationIsSet() const;
    void unsetOrganisation();
    void setOrganisation(std::shared_ptr<Organisation> value);
    /// <summary>
    /// The roles the user will be assigned once the invitation has been accepted.
    /// </summary>
    std::vector<std::shared_ptr<Role>>& getRoles();
    bool rolesIsSet() const;
    void unsetRoles();
    void setRoles(std::vector<std::shared_ptr<Role>> value);

protected:
    std::shared_ptr<Organisation> m_Organisation;
    bool m_OrganisationIsSet;
    std::vector<std::shared_ptr<Role>> m_Roles;
    bool m_RolesIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_Invitation__embedded_H_ */
