/**
 * Sensor Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "InvitationPost.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

InvitationPost::InvitationPost()
{
    m_Userid = U("");
    m_UseridIsSet = false;
    m_Organisationid = U("");
    m_OrganisationidIsSet = false;
    m_RoleidsIsSet = false;
}

InvitationPost::~InvitationPost()
{
}

void InvitationPost::validate()
{
    // TODO: implement validation
}

web::json::value InvitationPost::toJson() const
{
    web::json::value val = web::json::value::object();

    if(m_UseridIsSet)
    {
        val[U("userid")] = ModelBase::toJson(m_Userid);
    }
    if(m_OrganisationidIsSet)
    {
        val[U("organisationid")] = ModelBase::toJson(m_Organisationid);
    }
    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Roleids )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        if(jsonArray.size() > 0)
        {
            val[U("roleids")] = web::json::value::array(jsonArray);
        }
    }

    return val;
}

void InvitationPost::fromJson(web::json::value& val)
{
    if(val.has_field(U("userid")))
    {
        setUserid(ModelBase::stringFromJson(val[U("userid")]));
    }
    if(val.has_field(U("organisationid")))
    {
        setOrganisationid(ModelBase::stringFromJson(val[U("organisationid")]));
    }
    {
        m_Roleids.clear();
        std::vector<web::json::value> jsonArray;
        if(val.has_field(U("roleids")))
        {
        for( auto& item : val[U("roleids")].as_array() )
        {
            m_Roleids.push_back(ModelBase::stringFromJson(item));
        }
        }
    }
}

void InvitationPost::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    if(m_UseridIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + U("userid"), m_Userid));
        
    }
    if(m_OrganisationidIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + U("organisationid"), m_Organisationid));
        
    }
    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Roleids )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        
        if(jsonArray.size() > 0)
        {
            multipart->add(ModelBase::toHttpContent(namePrefix + U("roleids"), web::json::value::array(jsonArray), U("application/json")));
        }
    }
}

void InvitationPost::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    if(multipart->hasContent(U("userid")))
    {
        setUserid(ModelBase::stringFromHttpContent(multipart->getContent(U("userid"))));
    }
    if(multipart->hasContent(U("organisationid")))
    {
        setOrganisationid(ModelBase::stringFromHttpContent(multipart->getContent(U("organisationid"))));
    }
    {
        m_Roleids.clear();
        if(multipart->hasContent(U("roleids")))
        {

        web::json::value jsonArray = web::json::value::parse(ModelBase::stringFromHttpContent(multipart->getContent(U("roleids"))));
        for( auto& item : jsonArray.as_array() )
        {
            m_Roleids.push_back(ModelBase::stringFromJson(item));
        }
        }
    }
}

utility::string_t InvitationPost::getUserid() const
{
    return m_Userid;
}


void InvitationPost::setUserid(utility::string_t value)
{
    m_Userid = value;
    m_UseridIsSet = true;
}
bool InvitationPost::useridIsSet() const
{
    return m_UseridIsSet;
}

void InvitationPost::unsetUserid()
{
    m_UseridIsSet = false;
}

utility::string_t InvitationPost::getOrganisationid() const
{
    return m_Organisationid;
}


void InvitationPost::setOrganisationid(utility::string_t value)
{
    m_Organisationid = value;
    m_OrganisationidIsSet = true;
}
bool InvitationPost::organisationidIsSet() const
{
    return m_OrganisationidIsSet;
}

void InvitationPost::unsetOrganisationid()
{
    m_OrganisationidIsSet = false;
}

std::vector<utility::string_t>& InvitationPost::getRoleids()
{
    return m_Roleids;
}

void InvitationPost::setRoleids(std::vector<utility::string_t> value)
{
    m_Roleids = value;
    m_RoleidsIsSet = true;
}
bool InvitationPost::roleidsIsSet() const
{
    return m_RoleidsIsSet;
}

void InvitationPost::unsetRoleids()
{
    m_RoleidsIsSet = false;
}

}
}
}
}

