/**
 * Sensor Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.1-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "Invitation__embedded.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

Invitation__embedded::Invitation__embedded()
{
    m_OrganisationIsSet = false;
    m_RolesIsSet = false;
}

Invitation__embedded::~Invitation__embedded()
{
}

void Invitation__embedded::validate()
{
    // TODO: implement validation
}

web::json::value Invitation__embedded::toJson() const
{
    web::json::value val = web::json::value::object();

    if(m_OrganisationIsSet)
    {
        val[utility::conversions::to_string_t("organisation")] = ModelBase::toJson(m_Organisation);
    }
    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Roles )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        if(jsonArray.size() > 0)
        {
            val[utility::conversions::to_string_t("roles")] = web::json::value::array(jsonArray);
        }
    }

    return val;
}

void Invitation__embedded::fromJson(web::json::value& val)
{
    if(val.has_field(utility::conversions::to_string_t("organisation")))
    {
        if(!val[utility::conversions::to_string_t("organisation")].is_null())
        {
            std::shared_ptr<Organisation> newItem(new Organisation());
            newItem->fromJson(val[utility::conversions::to_string_t("organisation")]);
            setOrganisation( newItem );
        }
    }
    {
        m_Roles.clear();
        std::vector<web::json::value> jsonArray;
        if(val.has_field(utility::conversions::to_string_t("roles")))
        {
        for( auto& item : val[utility::conversions::to_string_t("roles")].as_array() )
        {
            if(item.is_null())
            {
                m_Roles.push_back( std::shared_ptr<Role>(nullptr) );
            }
            else
            {
                std::shared_ptr<Role> newItem(new Role());
                newItem->fromJson(item);
                m_Roles.push_back( newItem );
            }
        }
        }
    }
}

void Invitation__embedded::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(m_OrganisationIsSet)
    {
        if (m_Organisation.get())
        {
            m_Organisation->toMultipart(multipart, utility::conversions::to_string_t("organisation."));
        }
        
    }
    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Roles )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        
        if(jsonArray.size() > 0)
        {
            multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("roles"), web::json::value::array(jsonArray), utility::conversions::to_string_t("application/json")));
        }
    }
}

void Invitation__embedded::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(multipart->hasContent(utility::conversions::to_string_t("organisation")))
    {
        if(multipart->hasContent(utility::conversions::to_string_t("organisation")))
        {
            std::shared_ptr<Organisation> newItem(new Organisation());
            newItem->fromMultiPart(multipart, utility::conversions::to_string_t("organisation."));
            setOrganisation( newItem );
        }
    }
    {
        m_Roles.clear();
        if(multipart->hasContent(utility::conversions::to_string_t("roles")))
        {

        web::json::value jsonArray = web::json::value::parse(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("roles"))));
        for( auto& item : jsonArray.as_array() )
        {
            if(item.is_null())
            {
                m_Roles.push_back( std::shared_ptr<Role>(nullptr) );
            }
            else
            {
                std::shared_ptr<Role> newItem(new Role());
                newItem->fromJson(item);
                m_Roles.push_back( newItem );
            }
        }
        }
    }
}

std::shared_ptr<Organisation> Invitation__embedded::getOrganisation() const
{
    return m_Organisation;
}


void Invitation__embedded::setOrganisation(std::shared_ptr<Organisation> value)
{
    m_Organisation = value;
    m_OrganisationIsSet = true;
}
bool Invitation__embedded::organisationIsSet() const
{
    return m_OrganisationIsSet;
}

void Invitation__embedded::unsetOrganisation()
{
    m_OrganisationIsSet = false;
}

std::vector<std::shared_ptr<Role>>& Invitation__embedded::getRoles()
{
    return m_Roles;
}

void Invitation__embedded::setRoles(std::vector<std::shared_ptr<Role>> value)
{
    m_Roles = value;
    m_RolesIsSet = true;
}
bool Invitation__embedded::rolesIsSet() const
{
    return m_RolesIsSet;
}

void Invitation__embedded::unsetRoles()
{
    m_RolesIsSet = false;
}

}
}
}
}

