/**
 * Sensor Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.1-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "LocationCollection__embedded.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

LocationCollection__embedded::LocationCollection__embedded()
{
    m_LocationsIsSet = false;
}

LocationCollection__embedded::~LocationCollection__embedded()
{
}

void LocationCollection__embedded::validate()
{
    // TODO: implement validation
}

web::json::value LocationCollection__embedded::toJson() const
{
    web::json::value val = web::json::value::object();

    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Locations )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        if(jsonArray.size() > 0)
        {
            val[utility::conversions::to_string_t("locations")] = web::json::value::array(jsonArray);
        }
    }

    return val;
}

void LocationCollection__embedded::fromJson(web::json::value& val)
{
    {
        m_Locations.clear();
        std::vector<web::json::value> jsonArray;
        if(val.has_field(utility::conversions::to_string_t("locations")))
        {
        for( auto& item : val[utility::conversions::to_string_t("locations")].as_array() )
        {
            if(item.is_null())
            {
                m_Locations.push_back( std::shared_ptr<PlatformCollection__embedded_platforms>(nullptr) );
            }
            else
            {
                std::shared_ptr<PlatformCollection__embedded_platforms> newItem(new PlatformCollection__embedded_platforms());
                newItem->fromJson(item);
                m_Locations.push_back( newItem );
            }
        }
        }
    }
}

void LocationCollection__embedded::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Locations )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        
        if(jsonArray.size() > 0)
        {
            multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("locations"), web::json::value::array(jsonArray), utility::conversions::to_string_t("application/json")));
        }
    }
}

void LocationCollection__embedded::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    {
        m_Locations.clear();
        if(multipart->hasContent(utility::conversions::to_string_t("locations")))
        {

        web::json::value jsonArray = web::json::value::parse(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("locations"))));
        for( auto& item : jsonArray.as_array() )
        {
            if(item.is_null())
            {
                m_Locations.push_back( std::shared_ptr<PlatformCollection__embedded_platforms>(nullptr) );
            }
            else
            {
                std::shared_ptr<PlatformCollection__embedded_platforms> newItem(new PlatformCollection__embedded_platforms());
                newItem->fromJson(item);
                m_Locations.push_back( newItem );
            }
        }
        }
    }
}

std::vector<std::shared_ptr<PlatformCollection__embedded_platforms>>& LocationCollection__embedded::getLocations()
{
    return m_Locations;
}

void LocationCollection__embedded::setLocations(std::vector<std::shared_ptr<PlatformCollection__embedded_platforms>> value)
{
    m_Locations = value;
    m_LocationsIsSet = true;
}
bool LocationCollection__embedded::locationsIsSet() const
{
    return m_LocationsIsSet;
}

void LocationCollection__embedded::unsetLocations()
{
    m_LocationsIsSet = false;
}

}
}
}
}

