/**
 * Sensor Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * LocationCollection__embedded.h
 *
 * 
 */

#ifndef LocationCollection__embedded_H_
#define LocationCollection__embedded_H_


#include "../ModelBase.h"

#include "PlatformCollection__embedded_platforms.h"
#include <vector>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  LocationCollection__embedded
    : public ModelBase
{
public:
    LocationCollection__embedded();
    virtual ~LocationCollection__embedded();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// LocationCollection__embedded members

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<PlatformCollection__embedded_platforms>>& getLocations();
    bool locationsIsSet() const;
    void unsetLocations();
    void setLocations(std::vector<std::shared_ptr<PlatformCollection__embedded_platforms>> value);

protected:
    std::vector<std::shared_ptr<PlatformCollection__embedded_platforms>> m_Locations;
    bool m_LocationsIsSet;
};

}
}
}
}

#endif /* LocationCollection__embedded_H_ */
