/**
 * Sensor Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "LocationPost.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

LocationPost::LocationPost()
{
    m_Id = U("");
    m_Organisationid = U("");
    m_Description = U("");
    m_DescriptionIsSet = false;
    m_GroupidsIsSet = false;
}

LocationPost::~LocationPost()
{
}

void LocationPost::validate()
{
    // TODO: implement validation
}

web::json::value LocationPost::toJson() const
{
    web::json::value val = web::json::value::object();

    val[U("id")] = ModelBase::toJson(m_Id);
    val[U("organisationid")] = ModelBase::toJson(m_Organisationid);
    if(m_DescriptionIsSet)
    {
        val[U("description")] = ModelBase::toJson(m_Description);
    }
    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Groupids )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        if(jsonArray.size() > 0)
        {
            val[U("groupids")] = web::json::value::array(jsonArray);
        }
    }
    val[U("geoJson")] = ModelBase::toJson(m_GeoJson);

    return val;
}

void LocationPost::fromJson(web::json::value& val)
{
    setId(ModelBase::stringFromJson(val[U("id")]));
    setOrganisationid(ModelBase::stringFromJson(val[U("organisationid")]));
    if(val.has_field(U("description")))
    {
        setDescription(ModelBase::stringFromJson(val[U("description")]));
    }
    {
        m_Groupids.clear();
        std::vector<web::json::value> jsonArray;
        if(val.has_field(U("groupids")))
        {
        for( auto& item : val[U("groupids")].as_array() )
        {
            m_Groupids.push_back(ModelBase::stringFromJson(item));
        }
        }
    }
    std::shared_ptr<GeoJSONPoint> newGeoJson(new GeoJSONPoint());
    newGeoJson->fromJson(val[U("geoJson")]);
    setGeoJson( newGeoJson );
}

void LocationPost::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    multipart->add(ModelBase::toHttpContent(namePrefix + U("id"), m_Id));
    multipart->add(ModelBase::toHttpContent(namePrefix + U("organisationid"), m_Organisationid));
    if(m_DescriptionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + U("description"), m_Description));
        
    }
    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Groupids )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        
        if(jsonArray.size() > 0)
        {
            multipart->add(ModelBase::toHttpContent(namePrefix + U("groupids"), web::json::value::array(jsonArray), U("application/json")));
        }
    }
    m_GeoJson->toMultipart(multipart, U("geoJson."));
}

void LocationPost::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    setId(ModelBase::stringFromHttpContent(multipart->getContent(U("id"))));
    setOrganisationid(ModelBase::stringFromHttpContent(multipart->getContent(U("organisationid"))));
    if(multipart->hasContent(U("description")))
    {
        setDescription(ModelBase::stringFromHttpContent(multipart->getContent(U("description"))));
    }
    {
        m_Groupids.clear();
        if(multipart->hasContent(U("groupids")))
        {

        web::json::value jsonArray = web::json::value::parse(ModelBase::stringFromHttpContent(multipart->getContent(U("groupids"))));
        for( auto& item : jsonArray.as_array() )
        {
            m_Groupids.push_back(ModelBase::stringFromJson(item));
        }
        }
    }
    std::shared_ptr<GeoJSONPoint> newGeoJson(new GeoJSONPoint());
    newGeoJson->fromMultiPart(multipart, U("geoJson."));
    setGeoJson( newGeoJson );
}

utility::string_t LocationPost::getId() const
{
    return m_Id;
}


void LocationPost::setId(utility::string_t value)
{
    m_Id = value;
    
}
utility::string_t LocationPost::getOrganisationid() const
{
    return m_Organisationid;
}


void LocationPost::setOrganisationid(utility::string_t value)
{
    m_Organisationid = value;
    
}
utility::string_t LocationPost::getDescription() const
{
    return m_Description;
}


void LocationPost::setDescription(utility::string_t value)
{
    m_Description = value;
    m_DescriptionIsSet = true;
}
bool LocationPost::descriptionIsSet() const
{
    return m_DescriptionIsSet;
}

void LocationPost::unsetDescription()
{
    m_DescriptionIsSet = false;
}

std::vector<utility::string_t>& LocationPost::getGroupids()
{
    return m_Groupids;
}

void LocationPost::setGroupids(std::vector<utility::string_t> value)
{
    m_Groupids = value;
    m_GroupidsIsSet = true;
}
bool LocationPost::groupidsIsSet() const
{
    return m_GroupidsIsSet;
}

void LocationPost::unsetGroupids()
{
    m_GroupidsIsSet = false;
}

std::shared_ptr<GeoJSONPoint> LocationPost::getGeoJson() const
{
    return m_GeoJson;
}


void LocationPost::setGeoJson(std::shared_ptr<GeoJSONPoint> value)
{
    m_GeoJson = value;
    
}
}
}
}
}

