/**
 * Sensor Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "ObservationsPost.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

ObservationsPost::ObservationsPost()
{
    m_ResultsIsSet = false;
}

ObservationsPost::~ObservationsPost()
{
}

void ObservationsPost::validate()
{
    // TODO: implement validation
}

web::json::value ObservationsPost::toJson() const
{
    web::json::value val = web::json::value::object();

    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Results )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        if(jsonArray.size() > 0)
        {
            val[U("results")] = web::json::value::array(jsonArray);
        }
    }

    return val;
}

void ObservationsPost::fromJson(web::json::value& val)
{
    {
        m_Results.clear();
        std::vector<web::json::value> jsonArray;
        if(val.has_field(U("results")))
        {
        for( auto& item : val[U("results")].as_array() )
        {
            if(item.is_null())
            {
                m_Results.push_back( std::shared_ptr<UnivariateResult>(nullptr) );
            }
            else
            {
                std::shared_ptr<UnivariateResult> newItem(new UnivariateResult());
                newItem->fromJson(item);
                m_Results.push_back( newItem );
            }
        }
        }
    }
}

void ObservationsPost::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Results )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        
        if(jsonArray.size() > 0)
        {
            multipart->add(ModelBase::toHttpContent(namePrefix + U("results"), web::json::value::array(jsonArray), U("application/json")));
        }
    }
}

void ObservationsPost::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    {
        m_Results.clear();
        if(multipart->hasContent(U("results")))
        {

        web::json::value jsonArray = web::json::value::parse(ModelBase::stringFromHttpContent(multipart->getContent(U("results"))));
        for( auto& item : jsonArray.as_array() )
        {
            if(item.is_null())
            {
                m_Results.push_back( std::shared_ptr<UnivariateResult>(nullptr) );
            }
            else
            {
                std::shared_ptr<UnivariateResult> newItem(new UnivariateResult());
                newItem->fromJson(item);
                m_Results.push_back( newItem );
            }
        }
        }
    }
}

std::vector<std::shared_ptr<UnivariateResult>>& ObservationsPost::getResults()
{
    return m_Results;
}

void ObservationsPost::setResults(std::vector<std::shared_ptr<UnivariateResult>> value)
{
    m_Results = value;
    m_ResultsIsSet = true;
}
bool ObservationsPost::resultsIsSet() const
{
    return m_ResultsIsSet;
}

void ObservationsPost::unsetResults()
{
    m_ResultsIsSet = false;
}

}
}
}
}

