/**
 * Sensor Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * Organisation__links.h
 *
 * 
 */

#ifndef Organisation__links_H_
#define Organisation__links_H_


#include "../ModelBase.h"

#include "Organisation__links_self.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  Organisation__links
    : public ModelBase
{
public:
    Organisation__links();
    virtual ~Organisation__links();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Organisation__links members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Organisation__links_self> getSelf() const;
    bool selfIsSet() const;
    void unsetSelf();
    void setSelf(std::shared_ptr<Organisation__links_self> value);

protected:
    std::shared_ptr<Organisation__links_self> m_Self;
    bool m_SelfIsSet;
};

}
}
}
}

#endif /* Organisation__links_H_ */
