/**
 * Sensor Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * OrganisationCollection__embedded.h
 *
 * 
 */

#ifndef OrganisationCollection__embedded_H_
#define OrganisationCollection__embedded_H_


#include "../ModelBase.h"

#include "Organisation.h"
#include <vector>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  OrganisationCollection__embedded
    : public ModelBase
{
public:
    OrganisationCollection__embedded();
    virtual ~OrganisationCollection__embedded();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// OrganisationCollection__embedded members

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<Organisation>>& getOrganisations();
    bool organisationsIsSet() const;
    void unsetOrganisations();
    void setOrganisations(std::vector<std::shared_ptr<Organisation>> value);

protected:
    std::vector<std::shared_ptr<Organisation>> m_Organisations;
    bool m_OrganisationsIsSet;
};

}
}
}
}

#endif /* OrganisationCollection__embedded_H_ */
