/**
 * Sensor Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.1-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "PlatformPost.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

PlatformPost::PlatformPost()
{
    m_Id = utility::conversions::to_string_t("");
    m_IdIsSet = false;
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_Organisationid = utility::conversions::to_string_t("");
    m_OrganisationidIsSet = false;
    m_GroupidsIsSet = false;
    m_StreamidsIsSet = false;
    m_DeploymentsIsSet = false;
}

PlatformPost::~PlatformPost()
{
}

void PlatformPost::validate()
{
    // TODO: implement validation
}

web::json::value PlatformPost::toJson() const
{
    web::json::value val = web::json::value::object();

    if(m_IdIsSet)
    {
        val[utility::conversions::to_string_t("id")] = ModelBase::toJson(m_Id);
    }
    if(m_NameIsSet)
    {
        val[utility::conversions::to_string_t("name")] = ModelBase::toJson(m_Name);
    }
    if(m_OrganisationidIsSet)
    {
        val[utility::conversions::to_string_t("organisationid")] = ModelBase::toJson(m_Organisationid);
    }
    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Groupids )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        if(jsonArray.size() > 0)
        {
            val[utility::conversions::to_string_t("groupids")] = web::json::value::array(jsonArray);
        }
    }
    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Streamids )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        if(jsonArray.size() > 0)
        {
            val[utility::conversions::to_string_t("streamids")] = web::json::value::array(jsonArray);
        }
    }
    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Deployments )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        if(jsonArray.size() > 0)
        {
            val[utility::conversions::to_string_t("deployments")] = web::json::value::array(jsonArray);
        }
    }

    return val;
}

void PlatformPost::fromJson(web::json::value& val)
{
    if(val.has_field(utility::conversions::to_string_t("id")))
    {
        setId(ModelBase::stringFromJson(val[utility::conversions::to_string_t("id")]));
    }
    if(val.has_field(utility::conversions::to_string_t("name")))
    {
        setName(ModelBase::stringFromJson(val[utility::conversions::to_string_t("name")]));
    }
    if(val.has_field(utility::conversions::to_string_t("organisationid")))
    {
        setOrganisationid(ModelBase::stringFromJson(val[utility::conversions::to_string_t("organisationid")]));
    }
    {
        m_Groupids.clear();
        std::vector<web::json::value> jsonArray;
        if(val.has_field(utility::conversions::to_string_t("groupids")))
        {
        for( auto& item : val[utility::conversions::to_string_t("groupids")].as_array() )
        {
            m_Groupids.push_back(ModelBase::stringFromJson(item));
        }
        }
    }
    {
        m_Streamids.clear();
        std::vector<web::json::value> jsonArray;
        if(val.has_field(utility::conversions::to_string_t("streamids")))
        {
        for( auto& item : val[utility::conversions::to_string_t("streamids")].as_array() )
        {
            m_Streamids.push_back(ModelBase::stringFromJson(item));
        }
        }
    }
    {
        m_Deployments.clear();
        std::vector<web::json::value> jsonArray;
        if(val.has_field(utility::conversions::to_string_t("deployments")))
        {
        for( auto& item : val[utility::conversions::to_string_t("deployments")].as_array() )
        {
            if(item.is_null())
            {
                m_Deployments.push_back( std::shared_ptr<PlatformDeployment>(nullptr) );
            }
            else
            {
                std::shared_ptr<PlatformDeployment> newItem(new PlatformDeployment());
                newItem->fromJson(item);
                m_Deployments.push_back( newItem );
            }
        }
        }
    }
}

void PlatformPost::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("id"), m_Id));
        
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("name"), m_Name));
        
    }
    if(m_OrganisationidIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("organisationid"), m_Organisationid));
        
    }
    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Groupids )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        
        if(jsonArray.size() > 0)
        {
            multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("groupids"), web::json::value::array(jsonArray), utility::conversions::to_string_t("application/json")));
        }
    }
    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Streamids )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        
        if(jsonArray.size() > 0)
        {
            multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("streamids"), web::json::value::array(jsonArray), utility::conversions::to_string_t("application/json")));
        }
    }
    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Deployments )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        
        if(jsonArray.size() > 0)
        {
            multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("deployments"), web::json::value::array(jsonArray), utility::conversions::to_string_t("application/json")));
        }
    }
}

void PlatformPost::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(multipart->hasContent(utility::conversions::to_string_t("id")))
    {
        setId(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("id"))));
    }
    if(multipart->hasContent(utility::conversions::to_string_t("name")))
    {
        setName(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("name"))));
    }
    if(multipart->hasContent(utility::conversions::to_string_t("organisationid")))
    {
        setOrganisationid(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("organisationid"))));
    }
    {
        m_Groupids.clear();
        if(multipart->hasContent(utility::conversions::to_string_t("groupids")))
        {

        web::json::value jsonArray = web::json::value::parse(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("groupids"))));
        for( auto& item : jsonArray.as_array() )
        {
            m_Groupids.push_back(ModelBase::stringFromJson(item));
        }
        }
    }
    {
        m_Streamids.clear();
        if(multipart->hasContent(utility::conversions::to_string_t("streamids")))
        {

        web::json::value jsonArray = web::json::value::parse(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("streamids"))));
        for( auto& item : jsonArray.as_array() )
        {
            m_Streamids.push_back(ModelBase::stringFromJson(item));
        }
        }
    }
    {
        m_Deployments.clear();
        if(multipart->hasContent(utility::conversions::to_string_t("deployments")))
        {

        web::json::value jsonArray = web::json::value::parse(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("deployments"))));
        for( auto& item : jsonArray.as_array() )
        {
            if(item.is_null())
            {
                m_Deployments.push_back( std::shared_ptr<PlatformDeployment>(nullptr) );
            }
            else
            {
                std::shared_ptr<PlatformDeployment> newItem(new PlatformDeployment());
                newItem->fromJson(item);
                m_Deployments.push_back( newItem );
            }
        }
        }
    }
}

utility::string_t PlatformPost::getId() const
{
    return m_Id;
}


void PlatformPost::setId(utility::string_t value)
{
    m_Id = value;
    m_IdIsSet = true;
}
bool PlatformPost::idIsSet() const
{
    return m_IdIsSet;
}

void PlatformPost::unsetId()
{
    m_IdIsSet = false;
}

utility::string_t PlatformPost::getName() const
{
    return m_Name;
}


void PlatformPost::setName(utility::string_t value)
{
    m_Name = value;
    m_NameIsSet = true;
}
bool PlatformPost::nameIsSet() const
{
    return m_NameIsSet;
}

void PlatformPost::unsetName()
{
    m_NameIsSet = false;
}

utility::string_t PlatformPost::getOrganisationid() const
{
    return m_Organisationid;
}


void PlatformPost::setOrganisationid(utility::string_t value)
{
    m_Organisationid = value;
    m_OrganisationidIsSet = true;
}
bool PlatformPost::organisationidIsSet() const
{
    return m_OrganisationidIsSet;
}

void PlatformPost::unsetOrganisationid()
{
    m_OrganisationidIsSet = false;
}

std::vector<utility::string_t>& PlatformPost::getGroupids()
{
    return m_Groupids;
}

void PlatformPost::setGroupids(std::vector<utility::string_t> value)
{
    m_Groupids = value;
    m_GroupidsIsSet = true;
}
bool PlatformPost::groupidsIsSet() const
{
    return m_GroupidsIsSet;
}

void PlatformPost::unsetGroupids()
{
    m_GroupidsIsSet = false;
}

std::vector<utility::string_t>& PlatformPost::getStreamids()
{
    return m_Streamids;
}

void PlatformPost::setStreamids(std::vector<utility::string_t> value)
{
    m_Streamids = value;
    m_StreamidsIsSet = true;
}
bool PlatformPost::streamidsIsSet() const
{
    return m_StreamidsIsSet;
}

void PlatformPost::unsetStreamids()
{
    m_StreamidsIsSet = false;
}

std::vector<std::shared_ptr<PlatformDeployment>>& PlatformPost::getDeployments()
{
    return m_Deployments;
}

void PlatformPost::setDeployments(std::vector<std::shared_ptr<PlatformDeployment>> value)
{
    m_Deployments = value;
    m_DeploymentsIsSet = true;
}
bool PlatformPost::deploymentsIsSet() const
{
    return m_DeploymentsIsSet;
}

void PlatformPost::unsetDeployments()
{
    m_DeploymentsIsSet = false;
}

}
}
}
}

