/**
 * Sensor Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * PlatformCollection__embedded_platforms.h
 *
 * 
 */

#ifndef PlatformCollection__embedded_platforms_H_
#define PlatformCollection__embedded_platforms_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>
#include "Organisation__links.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  PlatformCollection__embedded_platforms
    : public ModelBase
{
public:
    PlatformCollection__embedded_platforms();
    virtual ~PlatformCollection__embedded_platforms();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// PlatformCollection__embedded_platforms members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getId() const;
    bool idIsSet() const;
    void unsetId();
    void setId(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Organisation__links> getLinks() const;
    bool linksIsSet() const;
    void unset_links();
    void setLinks(std::shared_ptr<Organisation__links> value);

protected:
    utility::string_t m_Id;
    bool m_IdIsSet;
    std::shared_ptr<Organisation__links> m__links;
    bool m__linksIsSet;
};

}
}
}
}

#endif /* PlatformCollection__embedded_platforms_H_ */
