/**
 * Sensor Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "PlatformCollection__embedded.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

PlatformCollection__embedded::PlatformCollection__embedded()
{
    m_PlatformsIsSet = false;
}

PlatformCollection__embedded::~PlatformCollection__embedded()
{
}

void PlatformCollection__embedded::validate()
{
    // TODO: implement validation
}

web::json::value PlatformCollection__embedded::toJson() const
{
    web::json::value val = web::json::value::object();

    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Platforms )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        if(jsonArray.size() > 0)
        {
            val[U("platforms")] = web::json::value::array(jsonArray);
        }
    }

    return val;
}

void PlatformCollection__embedded::fromJson(web::json::value& val)
{
    {
        m_Platforms.clear();
        std::vector<web::json::value> jsonArray;
        if(val.has_field(U("platforms")))
        {
        for( auto& item : val[U("platforms")].as_array() )
        {
            if(item.is_null())
            {
                m_Platforms.push_back( std::shared_ptr<PlatformCollection__embedded_platforms>(nullptr) );
            }
            else
            {
                std::shared_ptr<PlatformCollection__embedded_platforms> newItem(new PlatformCollection__embedded_platforms());
                newItem->fromJson(item);
                m_Platforms.push_back( newItem );
            }
        }
        }
    }
}

void PlatformCollection__embedded::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Platforms )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        
        if(jsonArray.size() > 0)
        {
            multipart->add(ModelBase::toHttpContent(namePrefix + U("platforms"), web::json::value::array(jsonArray), U("application/json")));
        }
    }
}

void PlatformCollection__embedded::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    {
        m_Platforms.clear();
        if(multipart->hasContent(U("platforms")))
        {

        web::json::value jsonArray = web::json::value::parse(ModelBase::stringFromHttpContent(multipart->getContent(U("platforms"))));
        for( auto& item : jsonArray.as_array() )
        {
            if(item.is_null())
            {
                m_Platforms.push_back( std::shared_ptr<PlatformCollection__embedded_platforms>(nullptr) );
            }
            else
            {
                std::shared_ptr<PlatformCollection__embedded_platforms> newItem(new PlatformCollection__embedded_platforms());
                newItem->fromJson(item);
                m_Platforms.push_back( newItem );
            }
        }
        }
    }
}

std::vector<std::shared_ptr<PlatformCollection__embedded_platforms>>& PlatformCollection__embedded::getPlatforms()
{
    return m_Platforms;
}

void PlatformCollection__embedded::setPlatforms(std::vector<std::shared_ptr<PlatformCollection__embedded_platforms>> value)
{
    m_Platforms = value;
    m_PlatformsIsSet = true;
}
bool PlatformCollection__embedded::platformsIsSet() const
{
    return m_PlatformsIsSet;
}

void PlatformCollection__embedded::unsetPlatforms()
{
    m_PlatformsIsSet = false;
}

}
}
}
}

