/**
 * Sensor Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.1-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "PlatformCollection__embedded_platforms.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

PlatformCollection__embedded_platforms::PlatformCollection__embedded_platforms()
{
    m_Id = utility::conversions::to_string_t("");
    m_IdIsSet = false;
    m__linksIsSet = false;
}

PlatformCollection__embedded_platforms::~PlatformCollection__embedded_platforms()
{
}

void PlatformCollection__embedded_platforms::validate()
{
    // TODO: implement validation
}

web::json::value PlatformCollection__embedded_platforms::toJson() const
{
    web::json::value val = web::json::value::object();

    if(m_IdIsSet)
    {
        val[utility::conversions::to_string_t("id")] = ModelBase::toJson(m_Id);
    }
    if(m__linksIsSet)
    {
        val[utility::conversions::to_string_t("_links")] = ModelBase::toJson(m__links);
    }

    return val;
}

void PlatformCollection__embedded_platforms::fromJson(web::json::value& val)
{
    if(val.has_field(utility::conversions::to_string_t("id")))
    {
        setId(ModelBase::stringFromJson(val[utility::conversions::to_string_t("id")]));
    }
    if(val.has_field(utility::conversions::to_string_t("_links")))
    {
        if(!val[utility::conversions::to_string_t("_links")].is_null())
        {
            std::shared_ptr<Organisation__links> newItem(new Organisation__links());
            newItem->fromJson(val[utility::conversions::to_string_t("_links")]);
            setLinks( newItem );
        }
    }
}

void PlatformCollection__embedded_platforms::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("id"), m_Id));
        
    }
    if(m__linksIsSet)
    {
        if (m__links.get())
        {
            m__links->toMultipart(multipart, utility::conversions::to_string_t("_links."));
        }
        
    }
}

void PlatformCollection__embedded_platforms::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(multipart->hasContent(utility::conversions::to_string_t("id")))
    {
        setId(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("id"))));
    }
    if(multipart->hasContent(utility::conversions::to_string_t("_links")))
    {
        if(multipart->hasContent(utility::conversions::to_string_t("_links")))
        {
            std::shared_ptr<Organisation__links> newItem(new Organisation__links());
            newItem->fromMultiPart(multipart, utility::conversions::to_string_t("_links."));
            setLinks( newItem );
        }
    }
}

utility::string_t PlatformCollection__embedded_platforms::getId() const
{
    return m_Id;
}


void PlatformCollection__embedded_platforms::setId(utility::string_t value)
{
    m_Id = value;
    m_IdIsSet = true;
}
bool PlatformCollection__embedded_platforms::idIsSet() const
{
    return m_IdIsSet;
}

void PlatformCollection__embedded_platforms::unsetId()
{
    m_IdIsSet = false;
}

std::shared_ptr<Organisation__links> PlatformCollection__embedded_platforms::getLinks() const
{
    return m__links;
}


void PlatformCollection__embedded_platforms::setLinks(std::shared_ptr<Organisation__links> value)
{
    m__links = value;
    m__linksIsSet = true;
}
bool PlatformCollection__embedded_platforms::linksIsSet() const
{
    return m__linksIsSet;
}

void PlatformCollection__embedded_platforms::unset_links()
{
    m__linksIsSet = false;
}

}
}
}
}

