/**
 * Sensor Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.1-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "RoleCollection__embedded.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

RoleCollection__embedded::RoleCollection__embedded()
{
    m_RolesIsSet = false;
}

RoleCollection__embedded::~RoleCollection__embedded()
{
}

void RoleCollection__embedded::validate()
{
    // TODO: implement validation
}

web::json::value RoleCollection__embedded::toJson() const
{
    web::json::value val = web::json::value::object();

    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Roles )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        if(jsonArray.size() > 0)
        {
            val[utility::conversions::to_string_t("roles")] = web::json::value::array(jsonArray);
        }
    }

    return val;
}

void RoleCollection__embedded::fromJson(web::json::value& val)
{
    {
        m_Roles.clear();
        std::vector<web::json::value> jsonArray;
        if(val.has_field(utility::conversions::to_string_t("roles")))
        {
        for( auto& item : val[utility::conversions::to_string_t("roles")].as_array() )
        {
            if(item.is_null())
            {
                m_Roles.push_back( std::shared_ptr<Role>(nullptr) );
            }
            else
            {
                std::shared_ptr<Role> newItem(new Role());
                newItem->fromJson(item);
                m_Roles.push_back( newItem );
            }
        }
        }
    }
}

void RoleCollection__embedded::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Roles )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        
        if(jsonArray.size() > 0)
        {
            multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("roles"), web::json::value::array(jsonArray), utility::conversions::to_string_t("application/json")));
        }
    }
}

void RoleCollection__embedded::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    {
        m_Roles.clear();
        if(multipart->hasContent(utility::conversions::to_string_t("roles")))
        {

        web::json::value jsonArray = web::json::value::parse(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("roles"))));
        for( auto& item : jsonArray.as_array() )
        {
            if(item.is_null())
            {
                m_Roles.push_back( std::shared_ptr<Role>(nullptr) );
            }
            else
            {
                std::shared_ptr<Role> newItem(new Role());
                newItem->fromJson(item);
                m_Roles.push_back( newItem );
            }
        }
        }
    }
}

std::vector<std::shared_ptr<Role>>& RoleCollection__embedded::getRoles()
{
    return m_Roles;
}

void RoleCollection__embedded::setRoles(std::vector<std::shared_ptr<Role>> value)
{
    m_Roles = value;
    m_RolesIsSet = true;
}
bool RoleCollection__embedded::rolesIsSet() const
{
    return m_RolesIsSet;
}

void RoleCollection__embedded::unsetRoles()
{
    m_RolesIsSet = false;
}

}
}
}
}

