/**
 * Sensor Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.1-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * Role.h
 *
 * 
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_Role_H_
#define IO_SWAGGER_CLIENT_MODEL_Role_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>
#include <vector>
#include "Organisation__links.h"
#include "Permission.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  Role
    : public ModelBase
{
public:
    Role();
    virtual ~Role();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Role members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getId() const;
    bool idIsSet() const;
    void unsetId();
    void setId(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Organisation__links> getLinks() const;
    bool linksIsSet() const;
    void unset_links();
    void setLinks(std::shared_ptr<Organisation__links> value);
    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<Permission>>& getPermissions();
    bool permissionsIsSet() const;
    void unsetPermissions();
    void setPermissions(std::vector<std::shared_ptr<Permission>> value);
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getType() const;
    bool typeIsSet() const;
    void unsetType();
    void setType(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    bool isImplied() const;
    bool impliedIsSet() const;
    void unsetImplied();
    void setImplied(bool value);

protected:
    utility::string_t m_Id;
    bool m_IdIsSet;
    std::shared_ptr<Organisation__links> m__links;
    bool m__linksIsSet;
    std::vector<std::shared_ptr<Permission>> m_Permissions;
    bool m_PermissionsIsSet;
    utility::string_t m_Type;
    bool m_TypeIsSet;
    bool m_Implied;
    bool m_ImpliedIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_Role_H_ */
