/**
 * Sensor Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.1-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "RolePost_permissions.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

RolePost_permissions::RolePost_permissions()
{
    m_Type = utility::conversions::to_string_t("");
    m_TypeIsSet = false;
}

RolePost_permissions::~RolePost_permissions()
{
}

void RolePost_permissions::validate()
{
    // TODO: implement validation
}

web::json::value RolePost_permissions::toJson() const
{
    web::json::value val = web::json::value::object();

    if(m_TypeIsSet)
    {
        val[utility::conversions::to_string_t("type")] = ModelBase::toJson(m_Type);
    }

    return val;
}

void RolePost_permissions::fromJson(web::json::value& val)
{
    if(val.has_field(utility::conversions::to_string_t("type")))
    {
        setType(ModelBase::stringFromJson(val[utility::conversions::to_string_t("type")]));
    }
}

void RolePost_permissions::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(m_TypeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("type"), m_Type));
        
    }
}

void RolePost_permissions::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(multipart->hasContent(utility::conversions::to_string_t("type")))
    {
        setType(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("type"))));
    }
}

utility::string_t RolePost_permissions::getType() const
{
    return m_Type;
}


void RolePost_permissions::setType(utility::string_t value)
{
    m_Type = value;
    m_TypeIsSet = true;
}
bool RolePost_permissions::typeIsSet() const
{
    return m_TypeIsSet;
}

void RolePost_permissions::unsetType()
{
    m_TypeIsSet = false;
}

}
}
}
}

