/**
 * Sensor Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.1-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * RolePost_permissions.h
 *
 * 
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_RolePost_permissions_H_
#define IO_SWAGGER_CLIENT_MODEL_RolePost_permissions_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  RolePost_permissions
    : public ModelBase
{
public:
    RolePost_permissions();
    virtual ~RolePost_permissions();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// RolePost_permissions members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getType() const;
    bool typeIsSet() const;
    void unsetType();
    void setType(utility::string_t value);

protected:
    utility::string_t m_Type;
    bool m_TypeIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_RolePost_permissions_H_ */
