/**
 * Sensor Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.1-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "SensingProcedureCollection__embedded.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

SensingProcedureCollection__embedded::SensingProcedureCollection__embedded()
{
    m_SensingproceduresIsSet = false;
}

SensingProcedureCollection__embedded::~SensingProcedureCollection__embedded()
{
}

void SensingProcedureCollection__embedded::validate()
{
    // TODO: implement validation
}

web::json::value SensingProcedureCollection__embedded::toJson() const
{
    web::json::value val = web::json::value::object();

    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Sensingprocedures )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        if(jsonArray.size() > 0)
        {
            val[utility::conversions::to_string_t("sensingprocedures")] = web::json::value::array(jsonArray);
        }
    }

    return val;
}

void SensingProcedureCollection__embedded::fromJson(web::json::value& val)
{
    {
        m_Sensingprocedures.clear();
        std::vector<web::json::value> jsonArray;
        if(val.has_field(utility::conversions::to_string_t("sensingprocedures")))
        {
        for( auto& item : val[utility::conversions::to_string_t("sensingprocedures")].as_array() )
        {
            if(item.is_null())
            {
                m_Sensingprocedures.push_back( std::shared_ptr<PlatformCollection__embedded_platforms>(nullptr) );
            }
            else
            {
                std::shared_ptr<PlatformCollection__embedded_platforms> newItem(new PlatformCollection__embedded_platforms());
                newItem->fromJson(item);
                m_Sensingprocedures.push_back( newItem );
            }
        }
        }
    }
}

void SensingProcedureCollection__embedded::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Sensingprocedures )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        
        if(jsonArray.size() > 0)
        {
            multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("sensingprocedures"), web::json::value::array(jsonArray), utility::conversions::to_string_t("application/json")));
        }
    }
}

void SensingProcedureCollection__embedded::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    {
        m_Sensingprocedures.clear();
        if(multipart->hasContent(utility::conversions::to_string_t("sensingprocedures")))
        {

        web::json::value jsonArray = web::json::value::parse(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("sensingprocedures"))));
        for( auto& item : jsonArray.as_array() )
        {
            if(item.is_null())
            {
                m_Sensingprocedures.push_back( std::shared_ptr<PlatformCollection__embedded_platforms>(nullptr) );
            }
            else
            {
                std::shared_ptr<PlatformCollection__embedded_platforms> newItem(new PlatformCollection__embedded_platforms());
                newItem->fromJson(item);
                m_Sensingprocedures.push_back( newItem );
            }
        }
        }
    }
}

std::vector<std::shared_ptr<PlatformCollection__embedded_platforms>>& SensingProcedureCollection__embedded::getSensingprocedures()
{
    return m_Sensingprocedures;
}

void SensingProcedureCollection__embedded::setSensingprocedures(std::vector<std::shared_ptr<PlatformCollection__embedded_platforms>> value)
{
    m_Sensingprocedures = value;
    m_SensingproceduresIsSet = true;
}
bool SensingProcedureCollection__embedded::sensingproceduresIsSet() const
{
    return m_SensingproceduresIsSet;
}

void SensingProcedureCollection__embedded::unsetSensingprocedures()
{
    m_SensingproceduresIsSet = false;
}

}
}
}
}

