/**
 * Sensor Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SensingProcedureCollection__embedded.h
 *
 * 
 */

#ifndef SensingProcedureCollection__embedded_H_
#define SensingProcedureCollection__embedded_H_


#include "../ModelBase.h"

#include "PlatformCollection__embedded_platforms.h"
#include <vector>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  SensingProcedureCollection__embedded
    : public ModelBase
{
public:
    SensingProcedureCollection__embedded();
    virtual ~SensingProcedureCollection__embedded();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// SensingProcedureCollection__embedded members

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<PlatformCollection__embedded_platforms>>& getSensingprocedures();
    bool sensingproceduresIsSet() const;
    void unsetSensingprocedures();
    void setSensingprocedures(std::vector<std::shared_ptr<PlatformCollection__embedded_platforms>> value);

protected:
    std::vector<std::shared_ptr<PlatformCollection__embedded_platforms>> m_Sensingprocedures;
    bool m_SensingproceduresIsSet;
};

}
}
}
}

#endif /* SensingProcedureCollection__embedded_H_ */
