/**
 * Sensor Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * StreamCollection__embedded.h
 *
 * 
 */

#ifndef StreamCollection__embedded_H_
#define StreamCollection__embedded_H_


#include "../ModelBase.h"

#include "Stream.h"
#include <vector>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  StreamCollection__embedded
    : public ModelBase
{
public:
    StreamCollection__embedded();
    virtual ~StreamCollection__embedded();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// StreamCollection__embedded members

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<Stream>>& getStreams();
    bool streamsIsSet() const;
    void unsetStreams();
    void setStreams(std::vector<std::shared_ptr<Stream>> value);

protected:
    std::vector<std::shared_ptr<Stream>> m_Streams;
    bool m_StreamsIsSet;
};

}
}
}
}

#endif /* StreamCollection__embedded_H_ */
