/**
 * Sensor Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.1-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * UnivariateResult.h
 *
 * 
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_UnivariateResult_H_
#define IO_SWAGGER_CLIENT_MODEL_UnivariateResult_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>
#include "Object.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  UnivariateResult
    : public ModelBase
{
public:
    UnivariateResult();
    virtual ~UnivariateResult();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// UnivariateResult members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getT() const;
    bool TIsSet() const;
    void unsett();
    void setT(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Object> getV() const;
    bool VIsSet() const;
    void unsetv();
    void setV(std::shared_ptr<Object> value);

protected:
    utility::string_t m_t;
    bool m_tIsSet;
    std::shared_ptr<Object> m_v;
    bool m_vIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_UnivariateResult_H_ */
