/**
 * Sensor Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "UserCollection__embedded.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

UserCollection__embedded::UserCollection__embedded()
{
    m_UsersIsSet = false;
}

UserCollection__embedded::~UserCollection__embedded()
{
}

void UserCollection__embedded::validate()
{
    // TODO: implement validation
}

web::json::value UserCollection__embedded::toJson() const
{
    web::json::value val = web::json::value::object();

    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Users )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        if(jsonArray.size() > 0)
        {
            val[U("users")] = web::json::value::array(jsonArray);
        }
    }

    return val;
}

void UserCollection__embedded::fromJson(web::json::value& val)
{
    {
        m_Users.clear();
        std::vector<web::json::value> jsonArray;
        if(val.has_field(U("users")))
        {
        for( auto& item : val[U("users")].as_array() )
        {
            if(item.is_null())
            {
                m_Users.push_back( std::shared_ptr<User>(nullptr) );
            }
            else
            {
                std::shared_ptr<User> newItem(new User());
                newItem->fromJson(item);
                m_Users.push_back( newItem );
            }
        }
        }
    }
}

void UserCollection__embedded::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Users )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        
        if(jsonArray.size() > 0)
        {
            multipart->add(ModelBase::toHttpContent(namePrefix + U("users"), web::json::value::array(jsonArray), U("application/json")));
        }
    }
}

void UserCollection__embedded::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    {
        m_Users.clear();
        if(multipart->hasContent(U("users")))
        {

        web::json::value jsonArray = web::json::value::parse(ModelBase::stringFromHttpContent(multipart->getContent(U("users"))));
        for( auto& item : jsonArray.as_array() )
        {
            if(item.is_null())
            {
                m_Users.push_back( std::shared_ptr<User>(nullptr) );
            }
            else
            {
                std::shared_ptr<User> newItem(new User());
                newItem->fromJson(item);
                m_Users.push_back( newItem );
            }
        }
        }
    }
}

std::vector<std::shared_ptr<User>>& UserCollection__embedded::getUsers()
{
    return m_Users;
}

void UserCollection__embedded::setUsers(std::vector<std::shared_ptr<User>> value)
{
    m_Users = value;
    m_UsersIsSet = true;
}
bool UserCollection__embedded::usersIsSet() const
{
    return m_UsersIsSet;
}

void UserCollection__embedded::unsetUsers()
{
    m_UsersIsSet = false;
}

}
}
}
}

