/**
 * Sensor Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * UserCollection__embedded.h
 *
 * 
 */

#ifndef UserCollection__embedded_H_
#define UserCollection__embedded_H_


#include "../ModelBase.h"

#include <vector>
#include "User.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  UserCollection__embedded
    : public ModelBase
{
public:
    UserCollection__embedded();
    virtual ~UserCollection__embedded();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// UserCollection__embedded members

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<User>>& getUsers();
    bool usersIsSet() const;
    void unsetUsers();
    void setUsers(std::vector<std::shared_ptr<User>> value);

protected:
    std::vector<std::shared_ptr<User>> m_Users;
    bool m_UsersIsSet;
};

}
}
}
}

#endif /* UserCollection__embedded_H_ */
