/**
 * Sensor Data API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * VocabularyCollection__embedded.h
 *
 * 
 */

#ifndef VocabularyCollection__embedded_H_
#define VocabularyCollection__embedded_H_


#include "../ModelBase.h"

#include "VocabularyCollection__embedded_results.h"
#include <vector>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  VocabularyCollection__embedded
    : public ModelBase
{
public:
    VocabularyCollection__embedded();
    virtual ~VocabularyCollection__embedded();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// VocabularyCollection__embedded members

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<VocabularyCollection__embedded_results>>& getResults();
    bool resultsIsSet() const;
    void unsetResults();
    void setResults(std::vector<std::shared_ptr<VocabularyCollection__embedded_results>> value);

protected:
    std::vector<std::shared_ptr<VocabularyCollection__embedded_results>> m_Results;
    bool m_ResultsIsSet;
};

}
}
}
}

#endif /* VocabularyCollection__embedded_H_ */
